// automatically generated by CMake! Only touch the info.cpp.in file!
#pragma once

// clang-format off

// version
#define CPP_TERMINAL_VERSION_MAJOR 1
#define CPP_TERMINAL_VERSION_MINOR 0
#define CPP_TERMINAL_VERSION_PATCH 0
#define CPP_TERMINAL_VERSION_COMPLETE "1.0.0"
#define CPP_TERMINAL_HOMEPAGE_URL "https://github.com/jupyter-xeus/cpp-terminal"
